import "./globals.css";
import type { Metadata } from "next";
import { nunito } from "@/font";
import ThemeAdapter from "@/lib/themeAdapter";
import SessionProvider from "@/components/counterpart/auth/sessionProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	header,
	footer,
}: Readonly<{
	children: React.ReactNode;
	header: React.ReactNode;
	footer: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased ${nunito.className} relative`}>
				<header className="sticky top-0 z-10">{header}</header>
				<main>{children}</main>
				<footer>{footer}</footer>
			</body>
			<ThemeAdapter />
			<SessionProvider />
		</html>
	);
}
